ALTER TABLE cidade
	ADD COLUMN criado timestamp DEFAULT CURRENT_TIMESTAMP,
        ADD COLUMN editado timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;



ALTER TABLE cliente
	ADD COLUMN criado timestamp DEFAULT CURRENT_TIMESTAMP,
        ADD COLUMN editado timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;